name: Captura automática de tuits

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          python -m playwright install
          playwright --version

      - name: Comprobar versión Python
        run: python --version

      - name: Ejecutar script capture_tweet.py
        run: |
          python capture_tweet.py
        continue-on-error: false

      - name: Subir capturas como artefactos
        uses: actions/upload-artifact@v3
        with:
          name: capturas
          path: tweet_*.png
