name: Captura automática de tuits

on:
  schedule:
    - cron: '*/15 * * * *'  # Ejecutar cada 15 minutos
  workflow_dispatch:        # Permite ejecutarlo manualmente desde GitHub

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          python -m playwright install

      - name: Ejecutar script de captura
        run: python capture_tweet.py

      - name: Subir capturas como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: capturas
          path: tweet_*.png

